apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}
  annotations:
    {{- include "webapp.bdpProxyAnotations" . | nindent 4 }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
    {{- include "webapp.bdpProxyLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ ternary "https" "http" (eq .Values.ssl.enabled true) }}
      protocol: TCP
      name: {{ ternary "https" "http" (eq .Values.ssl.enabled true) }}
  selector:
    {{- include "webapp.selectorLabels" . | nindent 4 }}
