[tool.black]
line-length = 120
extend-exclude = '''
(
.*migrations/*
)
'''

[tool.isort]
profile = "black"
line_length = 120
known_first_party = ['amap', 'forms', 'personnel', 'tasks', 'utils']
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
extend_skip_glob = ["*migrations/*"]